" ********************************************************************************* "
"                                                                                   "
"                                                     :::::   :::#:::       :       "
"  File: .vimrc                                         #        #          #       "
"                                                       #        #         : :      "
"  By: wangjia <wangjia@mitegral.com>                   #        #        :   :     "
"                                                       #        #       :=====:    "
"  Created: 2019/04/11 17:16:55 by wangjia           .  #        #      :       :   "
"  Updated: 2019/04/11 17:16:55 by wangjia            ++:     :::#:::  :         :  "
"                                                                                   "
" ********************************************************************************* "

let g:user_name = 'wangjia'
let g:user_email = 'jia.wang@mitegral.com'

set nocompatible
set encoding=utf8
set fileencoding=utf-8
set fileencodings=utf-8,gbk

set nu

""vim不清屏
set t_ti= t_te=
set t_Co=256

set sw=4
set ts=4
set shiftround
set expandtab
set et

set hlsearch
set autoindent
set noignorecase

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

"sp 右边显示
set spr

""下面一条语句时代码折叠
set fdm=indent
syntax on
filetype plugin indent on
set cursorcolumn
set cursorline

set tags+=./tags
set tags+=../tags
set tags+=../../tags

" 自动高亮光标所在单词
autocmd CursorMoved * silent! exe printf('match IncSearch /\<%s\>/', expand('<cword>'))

" Pathogen
 execute pathogen#infect()

" ctrlP
nnoremap <Leader>fu :CtrlPFunky<Cr>

" Plugin rainbow
let g:rainbow_active = 1 "0 if you want to enable it later via :RainbowToggle
"let g:rainbow_conf = {
"\   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
"\   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
"\   'operators': '_,_',
"\   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
"\   'separately': {
"\       '*': {},
"\       'tex': {
"\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
"\       },
"\       'lisp': {
"\           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
"\       },
"\       'vim': {
"\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
"\       },
"\       'html': {
"\           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
"\       },
"\       'css': 0,
"\   }
"\}

" AirLine
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
"let g:airline_theme='simple'

" tagbar
map <F2> :TagbarToggle<cr>
map <F3> :NERDTreeToggle<cr>

map <F5> :only<cr>

map <F9> :make build<cr>
map <F10> :make test<cr>
map <F11> :!go test '%:p'<cr>
autocmd VimEnter *.h  nested TagbarOpen
autocmd VimEnter *.go  nested TagbarOpen
autocmd VimEnter *.cpp  nested TagbarOpen
autocmd VimEnter *.c  nested TagbarOpen
let tagbar_left=1
let tagbar_width=25
let g:NERDTreeWinPos = "right"

" color molokai
colorscheme molokai
"let g:rehash256 = 1
"let g:molokai_original = 1

" NERDTree
"autocmd vimenter * NERDTree
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
